### ISSUE TITLE
Empty array getting returned from DB

### ISSUE THREAD

**Issue by randeepbhatia** [awspilot/dynamodb-oop#27] opened 2016-10-19 22:38 UTC
Hi I believe its part of a the recent update, of all my dynamodB requests, I see one last object to be completely empty.
It's happening with the scan operation.

DynamoDB.table('TableName') 
        .scan (function (err, data) {
            if (err) {
                cb(err, null);
            }
            cb(null, data);
        });

**Comment by databank** [comment] 2016-10-25 07:43
sorry for the late reply, I just noticed your post now,

can you provide details on how to reproduce this ?

also note that your error handling is missing the return:

```
if (err)
   return cb(err, null )
```

**Comment by TimMeade** [comment] 2016-11-12 22:35
I'm seeing this a lot.....  if I rerun something simple insert 2 of 5 will come back {}

**Comment by databank** [comment] 2016-11-23 20:00
Im closing it, I'm supposing empty data is because of the leftout "return"

**Closed by databank** 2016-11-23 20:00 UTC
